package cn.cslg.exam.model;
// Generated 2017-5-30 15:36:00 by Hibernate Tools 5.2.3.Final

/**
 * ExamUser generated by hbm2java
 */
public class ExamUser implements java.io.Serializable {

	private Integer id;
	private int eid;
	private int uid;
	private String title;
	private String username;
	private int score;
	private boolean done;
	private int createTime;
	private int time;

	public ExamUser() {
	}

	public ExamUser(int eid, int uid, String title, String username, int score, boolean done, int createTime,
			int time) {
		this.eid = eid;
		this.uid = uid;
		this.title = title;
		this.username = username;
		this.score = score;
		this.done = done;
		this.createTime = createTime;
		this.time = time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getEid() {
		return this.eid;
	}

	public void setEid(int eid) {
		this.eid = eid;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	public boolean isDone() {
		return this.done;
	}

	public void setDone(boolean done) {
		this.done = done;
	}

	public int getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(int createTime) {
		this.createTime = createTime;
	}

	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}



}
