package cn.cslg.exam.model;
// Generated 2017-5-30 15:36:00 by Hibernate Tools 5.2.3.Final

/**
 * Exam generated by hbm2java
 */
public class Exam implements java.io.Serializable {

	private Integer id;
	private String title;
	private int createTime;
	private int time;
	private int CSelect;
	private int CMultselect;
	private int CFill;
	private int CTf;

	public Exam() {
	}

	public Exam(String title, int createTime, int time, int CSelect, int CMultselect, int CFill, int CTf) {
		this.title = title;
		this.createTime = createTime;
		this.time = time;
		this.CSelect = CSelect;
		this.CMultselect = CMultselect;
		this.CFill = CFill;
		this.CTf = CTf;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(int createTime) {
		this.createTime = createTime;
	}

	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}

	public int getCSelect() {
		return this.CSelect;
	}

	public void setCSelect(int CSelect) {
		this.CSelect = CSelect;
	}

	public int getCMultselect() {
		return this.CMultselect;
	}

	public void setCMultselect(int CMultselect) {
		this.CMultselect = CMultselect;
	}

	public int getCFill() {
		return this.CFill;
	}

	public void setCFill(int CFill) {
		this.CFill = CFill;
	}

	public int getCTf() {
		return this.CTf;
	}

	public void setCTf(int CTf) {
		this.CTf = CTf;
	}

}
