package cn.cslg.exam.model;
// Generated 2017-5-30 15:36:00 by Hibernate Tools 5.2.3.Final

/**
 * QSelect generated by hbm2java
 */
public class QSelect implements java.io.Serializable {

	private Integer id;
	private String ques;
	private String item0;
	private String item1;
	private String item2;
	private String item3;
	private String answer;

	public QSelect() {
	}

	public QSelect(String ques, String item0, String item1, String item2, String item3, String answer) {
		this.ques = ques;
		this.item0 = item0;
		this.item1 = item1;
		this.item2 = item2;
		this.item3 = item3;
		this.answer = answer;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getQues() {
		return this.ques;
	}

	public void setQues(String ques) {
		this.ques = ques;
	}

	public String getItem0() {
		return this.item0;
	}

	public void setItem0(String item0) {
		this.item0 = item0;
	}

	public String getItem1() {
		return this.item1;
	}

	public void setItem1(String item1) {
		this.item1 = item1;
	}

	public String getItem2() {
		return this.item2;
	}

	public void setItem2(String item2) {
		this.item2 = item2;
	}

	public String getItem3() {
		return this.item3;
	}

	public void setItem3(String item3) {
		this.item3 = item3;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

}
